# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CYTabSwitchView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry', '~> 1.1.0'
  # Pods for CYTabSwitchView

  target 'CYTabSwitchViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CYTabSwitchViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
